---
# Install pip, virtualenv, and python project requirements

- name: groups necessary for web apps
  group: name={{ item }} 
         state=present
         system=yes
  with_items:
    - webworkers
  tags: 
    - app-groups

- name: users necessary for web apps
  user: name=webhead
        state=present
        group=webworkers
  tags:
    - app-users

- name: pip | install pip via yum
  yum: name=python-pip state=latest
  tags:
   - pip

- name: virtualenv | install virtualenv via pip
  pip: name=virtualenv
       state=present
  tags:
    - virtualenv

- name: virtualenv | create global storage directory
  file: path=/srv/virtualenv 
        state=directory 
        owner=root 
        group=webworkers 
        mode=0740
  tags: 
    - virtualenv

- name: app directory
  file: path=/srv/www
        state=directory 
        owner=webworker
        group=webworkers
        mode=0770
  tags: 
    - app 
    - app-folders

- name: requirements | install requirements.txt
  pip: requirements=/srv/www/{{ py_app_source_folder }}/requirements.txt
       virtualenv_command=/usr/bin/virtualenv
       virtualenv=/srv/virtualenv/{{ py_app_virtualenv_folder }}
  tags:
    - app
    - app-requirements
